#!/bin/sh

CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build main.go
tar cfz zoneinfo.tar.gz /usr/share/zoneinfo
curl -o ca-certificates.crt https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt

docker build -t go-server .

rm -rf ./main
rm -rf ./ca-certificates.crt
rm -rf zoneinfo.tar.gz
